// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/16/2025, 1:30:06 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/ziqi.xu/Work/Learn/side_project/note/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ziqi.xu/Work/Learn/side_project/note/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ziqi.xu/Work/Learn/side_project/note/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ziqi.xu/Work/Learn/side_project/note/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ziqi.xu/Work/Learn/side_project/note/plugins/**/*.{js,ts,mjs}","/Users/ziqi.xu/Work/Learn/side_project/note/composables/**/*.{js,ts,mjs}","/Users/ziqi.xu/Work/Learn/side_project/note/utils/**/*.{js,ts,mjs}","/Users/ziqi.xu/Work/Learn/side_project/note/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ziqi.xu/Work/Learn/side_project/note/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ziqi.xu/Work/Learn/side_project/note/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ziqi.xu/Work/Learn/side_project/note/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;